version: '3
services:
  db:
    image: postgres:14.2-aipine
    container_name: demo-postgres-14.2
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    conmand:
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  demo-web:
    build:
    conmand: "./bin/rails servere"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - app-storage:/rail/storage
    depends_on:
      - db

    volumes:
      postgres_data:{}
      app-storage: {}
    networks:
      demo_default:
    
       






































































































































































































































































































































'































